import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{Project}from'../src/project.ts';import{workflow}from'../src/workflow.ts';import{defaults,safeSitePath}from'../src/core.ts';import{decodeImage}from'../src/images.ts';import{attachmentPaths}from'../src/attachment-paths.ts';
test('uploaded photo has explicit usable paths, aliases and original bytes without an image model call',async()=>{
 const root=await mkdtemp(join(tmpdir(),'aiwe-upload-path-'));try{
  const p=new Project(join(root,'project'));await p.init(null);const data='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZuoAAAAASUVORK5CYII=',image={...decodeImage({data,name:'image.png'}),data,use:'auto'};let calls=0;
  const model:any=async(client:any,_:any,input:any)=>{calls++;if(calls===1){assert.equal(input.attachments[0].path,'site/assets/'+image.id);return {value:{action:'read',paths:['/api/images/'+image.id]}};}if(calls===2){assert.ok(input.files['site/assets/'+image.id]);return {value:{action:'implement',needsVerification:true,files:[{path:'site/index.html',content:input.files['site/index.html'].replace('</body>','<img src="'+input.attachments[0].publicUrl+'" alt="Dodaná fotografie"></body>')}]}};}return {value:{status:'PASS',requiredFixes:[]}};};
  const result=await workflow(p,[{provider:'openai',key:'fake',...defaults.openai}],'Use this photograph',join(root,'drafts'),()=>{},model,undefined,[image],{check:(async()=>({passed:true,errors:[],checks:[],screenshots:[]})) as any});assert.equal(result.tests.passed,true);assert.ok((await p.binary(result.commit,'site/assets/'+image.id)).equals(image.bytes));assert.equal(calls,3);assert.equal(result.imageResults.length,0);
  const resolve=attachmentPaths([{...image,use:'website'}]);assert.equal(resolve('image.png'),'site/assets/'+image.id);assert.equal(resolve('../config.json'),'../config.json');assert.throws(()=>safeSitePath(root,resolve('../config.json')));
  const unplaced={...image,id:'other.png'};const referenceModel:any=async(_:any,__:any,input:any)=>({value:{action:'implement',files:[{path:'site/index.html',content:input.files['site/index.html']+'\n<!-- inspired -->'}]}});await workflow(p,[{provider:'openai',key:'fake',...defaults.openai}],'Use as inspiration',join(root,'drafts'),()=>{},referenceModel,undefined,[unplaced],{check:(async()=>({passed:true,errors:[],checks:[],screenshots:[]})) as any});assert.ok(!(await p.files())['site/assets/other.png']);
 }finally{await rm(root,{recursive:true,force:true,maxRetries:3,retryDelay:100});}
});
