import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {Project} from '../src/project.ts';import {realitySnapshot} from '../src/reality-source.ts';
test('authenticated hosting reader returns actual HTTP files and binary bytes without publishing or changing either Git',async()=>{
 const root=await mkdtemp(join(tmpdir(),'sitetiller-hosted-endpoint-'));let child:any,web:any;try{
  const project=new Project(join(root,'project'));await project.init(null);const head=await project.head(),original=(await project.files())['site/index.html'];let content=original,reads=0;
  web=createServer((_req:any,res:any)=>{reads++;res.end(content);});await new Promise<void>(resolve=>web.listen(0,'127.0.0.1',resolve));const site='http://127.0.0.1:'+web.address().port+'/';
  const port=23400+Math.floor(Math.random()*100),publisher='http://127.0.0.1:'+port;child=spawn(process.execPath,[fileURLToPath(new URL('../src/publisher.ts',import.meta.url))],{env:{...process.env,PORT:String(port),SITETILLER_DATA_DIR:root,SITETILLER_PRODUCTION_GIT:project.root,SITETILLER_PRODUCTION_URL:site,SITETILLER_SITE_URL:'https://example.org/',SITETILLER_PUBLISH_TOKEN:'fixture-token'},stdio:'ignore'});
  for(let i=0;i<80;i++){try{if((await fetch(publisher+'/snapshot')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,100));}assert.equal(reads,0);
  const snapshot=await realitySnapshot('https://example.org/',publisher+'/publish','fixture-token');assert.equal(snapshot.files['site/index.html'],original);assert.equal(snapshot.evidence.catalogVerified,true);assert.equal(await project.head(),head);
  content=original.replace('Nový web','External live change');const changed=await realitySnapshot('https://example.org/',publisher+'/publish','fixture-token');assert.equal(changed.evidence.catalogVerified,false);assert.match(changed.files['site/index.html'],/External live change/);assert.equal(await project.head(),head);
 }finally{if(child?.exitCode===null){const stopped=new Promise(r=>child.once('exit',r));child.kill();await stopped;}if(web)await new Promise<void>(resolve=>web.close(()=>resolve()));await rm(root,{recursive:true,force:true});}
});
