import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {browserChecks} from '../src/checks.ts';
import {initialTeam,initialImages,migrateAgentConfig} from '../src/team.ts';
test('removing the simple image capability preserves chosen agent models and the remaining image choices',()=>{const roles=initialTeam();roles.verify.model='custom-verifier';const config:any={agentArchitecture:3,roles,imageModels:{precise:'gpt-image-2',fast:'gpt-image-2.5-flare',cheap:'gpt-image-2'},password:'unchanged'};assert.equal(migrateAgentConfig(config),true);assert.equal(config.roles.verify.model,'custom-verifier');assert.deepEqual(config.imageModels,{precise:'gpt-image-2',fast:'gpt-image-2.5-flare'});assert.equal(config.password,'unchanged');assert.equal(migrateAgentConfig(config),false);assert.equal(Object.keys(initialImages()).length,2);});
test('trusted pixel evidence measures PNG and WebP transparency despite website canvas tampering',async()=>{
 const {chromium}=await import('playwright'),browser=await chromium.launch({headless:true,...(process.env.SITETILLER_BROWSER_EXECUTABLE?{executablePath:process.env.SITETILLER_BROWSER_EXECUTABLE}:{})}),root=await mkdtemp(join(tmpdir(),'sitetiller-pixels-'));try{
  const page=await browser.newPage();const images=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2;canvas.height=1;const context=canvas.getContext('2d')!;context.fillStyle='red';context.fillRect(1,0,1,1);const transparent={png:canvas.toDataURL('image/png'),webp:canvas.toDataURL('image/webp')};context.fillRect(0,0,1,1);return {...transparent,opaque:canvas.toDataURL('image/png')};});await browser.close();await mkdir(join(root,'site/assets'),{recursive:true});const files:any={'site/index.html':'<!doctype html><html><head><title>Pixels</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><img src="assets/png.png" alt="PNG"><img src="assets/webp.webp" alt="WebP"><script>HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},getImageData(){return {data:new Uint8ClampedArray([0,0,0,255,0,0,0,255])}}});</script></body></html>'};
  for(const [key,data] of Object.entries(images)){const path='site/assets/'+key+(key==='webp'?'.webp':'.png');files[path]='[Binary image asset]';await writeFile(join(root,path),Buffer.from(data.split(',')[1],'base64'));}
  const evidence=await browserChecks(root,files,[],['site/assets/opaque.png']);assert.equal(evidence.passed,true,evidence.errors.join(';'));assert.equal(evidence.imageEvidence.length,3);for(const item of evidence.imageEvidence){assert.equal(item.checked,true);assert.equal(item.totalPixels,2);assert.equal(item.hasTransparentPixels,!item.path.includes('opaque'));assert.equal(item.transparentPixels,item.path.includes('opaque')?0:1);}
 }finally{await browser.close();await rm(root,{recursive:true,force:true});}
});
