import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {initialTeam,initialImages} from '../src/team.ts';
test('progress streams action and inline model without a duplicate sentence and only errors retain expandable details',async()=>{
 const {chromium}=await import('playwright'),browser=await chromium.launch({headless:true,...(process.env.SITETILLER_BROWSER_EXECUTABLE?{executablePath:process.env.SITETILLER_BROWSER_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),head='a'.repeat(40),event={jobId:'work',kind:'edit',stage:'orchestrate',status:'running',message:'Přemýšlím.',model:'gpt-6.1-sol'},request={id:'work',sequence:1,status:'running',prompt:'Změň barvu',progress:[event]};let state:any={head,busy:true,job:{id:'work',kind:'edit',status:'running'},events:[event],requests:[request],reviewRuns:[],roles:initialTeam(),imageModels:initialImages(),releases:[],history:[{commit:head}],previewUrl:'/preview/',publishConfigured:false,hasDraftSteps:true,hasLoadedReality:true,providers:[],siteUrl:''};
 await page.route('http://fixture.test/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.startsWith('/api/'))return route.fulfill({json:path==='/api/state'?state:path==='/api/session'?{authenticated:true,configured:true}:{models:[],issues:[],optionalIssues:[],errors:[]}});if(path.startsWith('/preview/'))return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><title>Fixture</title></head><body>Preview</body></html>'});const name=path==='/'?'index.html':path.slice(1);return route.fulfill({contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html',body:await readFile(new URL('../public/'+name,import.meta.url),'utf8')});});
 await page.addInitScript(()=>localStorage.setItem('sitetiller-language','cs'));await page.goto('http://fixture.test/');await page.locator('.live-progress h3').waitFor();assert.equal(await page.locator('.live-progress>summary').isHidden(),true);assert.ok((await page.locator('.live-progress h3').textContent()).startsWith('Přemýšlí'));assert.equal(await page.locator('.live-progress .actor-label').textContent(),'gpt-6.1-sol');assert.equal(await page.locator('.live-progress h3 .busy-dots').count(),1);assert.ok(!(await page.locator('.live-progress').textContent()).includes('Přemýšlím.'));
 const done=[event,{...event,stage:'build',status:'completed',message:'Barva byla změněna.'},{jobId:'work',kind:'edit',stage:'ready',commit:head}];state={...state,busy:false,job:{id:'work',kind:'edit',status:'ready'},events:done,requests:[{...request,status:'ready',commit:head,progress:done}]};await page.locator('.result-preview-row>.response-text').waitFor();assert.equal(await page.locator('.progress-group summary').count(),0);assert.equal(await page.locator('.result-preview-row>.response-text').textContent(),'Barva byla změněna.');state={...state,events:done.filter(e=>e.stage!=='ready').concat({jobId:'work',kind:'edit',stage:'ready'}),requests:[{...request,status:'answered',commit:null,progress:done.filter(e=>e.stage!=='ready').concat({jobId:'work',kind:'edit',stage:'ready'})}]};await page.waitForFunction(()=>!document.querySelector('.progress-group .show-version'));assert.equal(await page.locator('.progress-group summary').count(),0);assert.equal(await page.locator('.progress-group.result-complete').count(),0);state={...state,job:{id:'work',kind:'edit',status:'failed'},events:[event,{jobId:'work',kind:'edit',stage:'failed',message:'Fixture error'}],requests:[{...request,status:'failed',commit:null,progress:[event,{jobId:'work',kind:'edit',stage:'failed',message:'Fixture error'}]}]};await page.locator('.progress-group summary').waitFor();assert.ok((await page.locator('.progress-group summary').textContent()).includes('Fixture error'));await page.locator('.progress-group summary').click();assert.equal(await page.locator('.progress-detail').isVisible(),true);
 }finally{await browser.close();}
});
