import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {spawn} from 'node:child_process';import {scryptSync} from 'node:crypto';import {Project} from '../src/project.ts';import {initialTeam,initialImages} from '../src/team.ts';
test('load dialog distinguishes publications from steps; rewind adds no step and clear-all preserves published versions',async()=>{
 const data=await mkdtemp(join(tmpdir(),'sitetiller-load-history-'));let child:any,browser:any;
 try{
  const project=new Project(join(data,'project'));await project.init(null);const html=(name:string)=>'<!doctype html><html><head><title>'+name+'</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1>'+name+'</h1></body></html>';
  await project.write({'site/index.html':html('Published')});const published=await project.commit('Published');await project.write({'site/index.html':html('Step one')});const first=await project.commit('Step one');await project.write({'site/index.html':html('Step two')});const head=await project.commit('Step two');
  const password='test-password-sitetiller',salt='salt',release={id:'release-8',number:8,commit:published,publishedAt:'2026-10-06T12:00:00Z',previousCommit:null,description:'Published',summary:''};
  await writeFile(join(data,'config.json'),JSON.stringify({password:{salt,hash:scryptSync(password,salt,64).toString('hex')},providers:{openai:{key:''},anthropic:{key:''}},roles:initialTeam(),imageModels:initialImages(),agentArchitecture:3,automaticReasoningPolicy:1,publishedCommit:published,publishedThrough:0,releases:[release],requests:[{id:'one',prompt:'First edit',commit:first,status:'ready',sequence:1},{id:'two',prompt:'Second edit',commit:head,status:'ready',sequence:2},{id:'failed',prompt:'Failed attempt',status:'failed',sequence:3}]}));
  const port=20400+Math.floor(Math.random()*150),origin='http://127.0.0.1:'+port;child=spawn(process.execPath,[fileURLToPath(new URL('./fixtures/provider-server.mjs',import.meta.url))],{env:{...process.env,SITETILLER_DATA_DIR:data,HOST:'127.0.0.1',PORT:String(port),SITETILLER_ORIGIN:origin},stdio:'ignore'});
  let ready=false;for(let i=0;i<100;i++){try{if((await fetch(origin+'/health')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
  const login=await fetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})}),cookie=login.headers.get('set-cookie')!.split(';')[0];const state=async()=>await(await fetch(origin+'/api/state',{headers:{Cookie:cookie}})).json() as any;
  const post=(input:any)=>fetch(origin+'/api/restore',{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(input)});
  assert.equal((await post({commit:first,expectedHead:head,historyMode:'clear-all'})).status,400);assert.equal(await project.head(),head);assert.equal((await post({commit:published,expectedHead:head,historyMode:'rewind'})).status,400);
  await writeFile(join(project.root,'project-manifest.json'),JSON.stringify({version:1,cache:true}));await writeFile(join(project.root,'site','unsaved.txt'),'Unsaved website content');const blocked=await post({commit:first,expectedHead:head,historyMode:'rewind',stepId:'one'});assert.equal(blocked.status,400);assert.ok((await blocked.json()).error.includes('neuložené změny'));assert.equal(await project.head(),head);await rm(join(project.root,'site','unsaved.txt'));
  const {chromium}=await import('playwright');browser=await chromium.launch({...(process.env.SITETILLER_BROWSER_EXECUTABLE?{executablePath:process.env.SITETILLER_BROWSER_EXECUTABLE}:{}),headless:true});const page=await browser.newPage();await page.context().addCookies([{name:'sitetiller',value:cookie.slice('sitetiller='.length),url:origin}]);await page.goto(origin);
  await page.locator('#timeline .show-version[data-commit="'+first+'"]').click();await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-preview').textContent(),'Vrátit se sem');assert.equal(await page.locator('#restore-clear-label').textContent(),'Smazat následující úpravy');assert.equal(await page.locator('#restore-clear-previous').isChecked(),false);assert.ok(!(await page.locator('#restore-confirm').textContent())?.includes('commit'));
  await page.locator('#restore-clear-previous').check();await page.locator('#cancel-restore').click();assert.equal(await project.head(),head);await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-clear-previous').isChecked(),false);await page.locator('#restore-clear-previous').check();await page.locator('#confirm-restore').click();await page.locator('#restore-confirm').waitFor({state:'hidden'});
  const rewound=await state();assert.equal(rewound.head,first);assert.equal(JSON.parse(await readFile(join(project.root,'project-manifest.json'),'utf8')).cache,true);assert.deepEqual(rewound.requests.map((r:any)=>r.id),['one']);assert.equal(rewound.job,null);assert.deepEqual(rewound.releases,[release]);assert.equal((await fetch(origin+'/preview/versions/'+head+'/')).status,404);assert.equal(await project.git(['log','-1','--format=%s']),'Step one');assert.equal(JSON.parse(await readFile(join(data,'config.json'),'utf8')).requestSequence,3);
  await page.locator('#history-toggle').click();assert.equal(await page.locator('#history .show-version').getAttribute('aria-label'),'Náhled této verze');await page.locator('#history .show-version').click();await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-clear-previous').isChecked(),true);await page.locator('#cancel-restore').click();await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-clear-label').textContent(),'Odstranit všechny rozpracované úpravy');assert.equal(await page.locator('#restore-clear-previous').isChecked(),true);await page.locator('#restore-clear-previous').check();await page.locator('#confirm-restore').click();await page.locator('#restore-confirm').waitFor({state:'hidden'});
  const cleared=await state();assert.equal(cleared.requests.length,1);assert.equal(cleared.requests[0].restoredFrom,published);assert.equal(cleared.requests[0].sequence,4);assert.equal(cleared.publishedCommit,published);assert.deepEqual(cleared.releases,[release]);assert.equal(cleared.contentChanged,false);assert.ok(!cleared.history.some((h:any)=>h.commit===first));assert.equal((await fetch(origin+'/preview/versions/'+first+'/')).status,404);assert.equal(await page.locator('#edits-tab').getAttribute('aria-selected'),'true');assert.equal(await project.git(['rev-parse',cleared.head+':site']),await project.git(['rev-parse',published+':site']));
  const retry=await post({commit:published,expectedHead:cleared.head,releaseId:release.id,historyMode:'clear-all'});assert.equal(retry.status,200);await project.git(['reset','--hard',published]);const alreadyCurrent=await post({commit:published,expectedHead:published,releaseId:release.id,historyMode:'clear-all'});assert.equal(alreadyCurrent.status,200);assert.equal((await state()).head,published);assert.equal((await state()).contentChanged,false);assert.deepEqual((await state()).releases,[release]);
 }finally{await browser?.close();if(child&&child.exitCode===null){const exited=new Promise(r=>child.once('exit',r));child.kill();await exited;}await rm(data,{recursive:true,force:true,maxRetries:5,retryDelay:200});}
});

