import test from 'node:test';import assert from 'node:assert/strict';
// These assertions exercise Czech labels independently of the installation default.
const previousStorage=globalThis.localStorage;
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=> 'cs'}});
const {compactProgress}=await import('../public/presentation.js');
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:previousStorage});
test('actual verifier model is shown while automatic tests have no invented model',()=>{
 const roles={primary:{model:'gpt-6.1-sol'},ui:{model:'claude-sonnet-5-5'},verify:{model:'gpt-6-luna'}};
 const events:any[]=[{jobId:'one',kind:'edit',stage:'build',model:'gpt-6.1-sol'},{jobId:'one',kind:'edit',stage:'test',status:'running'}];assert.equal(compactProgress(events,null,true,roles)[0].rows[0].label,'Technická kontrola');
 events.push({jobId:'one',kind:'edit',stage:'verify',model:'gpt-6-luna',status:'running'});assert.equal(compactProgress(events,null,true,roles)[0].rows[0].label,'gpt-6-luna: kontrola');
});
test('full edit and review transcripts remain accessible after the bounded event feed is trimmed',()=>{const edit=[{stage:'design',model:'D'},{stage:'build',message:'Full implementation summary'},{stage:'test',message:'Full checks'},{stage:'ready',commit:'after'}],review=[{stage:'review',message:'Full review',checks:[{passed:true}]},{stage:'ready',message:'Passed'}];const groups=compactProgress([],null,false,{},[{id:'e',prompt:'Full request',progress:edit,status:'ready',baseCommit:'before',commit:'after'}],[{id:'r',progress:review}]);assert.equal(groups.length,2);assert.equal(groups[0].rows[0].events,edit);assert.equal(groups[1].rows[0].events,review);assert.equal(groups[1].rows[0].label,'Revize hotovo');});
test('one stable status row progresses through design, implementation, control and Hotovo with full request and rollback boundary',()=>{const request={id:'one',prompt:'Full user request',baseCommit:'before'},events:any[]=[{jobId:'one',kind:'edit',stage:'design',model:'D',status:'running'}];const group=()=>compactProgress(events,{id:'one',kind:'edit',status:'running'},true,{},[request])[0];const key=group().rows[0].key;assert.equal(group().rows.length,1);assert.equal(group().rows[0].label,'D: návrh');assert.equal(group().prompt,request.prompt);events.push({jobId:'one',kind:'edit',stage:'design',status:'completed',plan:{summary:'Plan'}},{jobId:'one',kind:'edit',stage:'build',model:'B'});assert.equal(group().rows[0].label,'B: provádění');events.push({jobId:'one',kind:'edit',stage:'test',model:'T'});assert.equal(group().rows[0].label,'T: kontrola');events.push({jobId:'one',kind:'edit',stage:'ready',commit:'after'});assert.equal(group().rows.length,1);assert.equal(group().rows[0].key,key);assert.equal(group().rows[0].label,'Hotovo');assert.equal(group().rows[0].running,false);assert.equal(group().baseCommit,'before');assert.equal(group().rows[0].events.length,5);});
test('review combines content and outcome; only passed review gets Revize hotovo',()=>{const events:any[]=[{jobId:'r',kind:'review',stage:'review',model:'R',status:'running'}];assert.equal(compactProgress(events)[0].rows[0].label,'R: revize');events.push({jobId:'r',kind:'review',stage:'review',status:'completed',checks:[{passed:true,summary:'Checked'}]},{jobId:'r',kind:'review',stage:'ready'});const row=compactProgress(events)[0].rows[0];assert.equal(row.label,'Revize hotovo');assert.equal(row.events.length,3);events.push({jobId:'r',kind:'review',stage:'failed'});assert.equal(compactProgress(events)[0].rows[0].label,'Revize neprošla');});
test('durable request journal survives trimmed events without duplicating active jobs',()=>{const requests=[{id:'old',prompt:'Archived full prompt',status:'ready',baseCommit:'before',commit:'after',plan:{summary:'Plan'}},{id:'new',prompt:'Pending',status:'running'}];const groups=compactProgress([],{id:'new',kind:'edit',status:'running'},true,{ui:{model:'D'}},requests);assert.equal(groups.length,2);assert.equal(groups[0].prompt,'Archived full prompt');assert.equal(groups[0].rows[0].label,'Hotovo');assert.equal(groups[1].rows[0].label,'D: návrh');});
test('legacy events and publication failures remain readable',()=>{const legacy:any[]=[{stage:'design',model:'D',at:'1'},{stage:'build',model:'B'},{stage:'ready'},{stage:'design',model:'D',at:'2'},{stage:'failed'}];assert.equal(compactProgress(legacy).length,2);assert.equal(compactProgress(legacy)[0].rows.length,1);assert.equal(compactProgress(legacy)[1].rows[0].error,true);const events:any[]=[{jobId:'p',kind:'publish',stage:'publish'}];assert.equal(compactProgress(events)[0].rows[0].running,true);events.push({jobId:'p',kind:'publish',stage:'failed'});assert.equal(compactProgress(events)[0].rows[0].label,'Publikování selhalo');});

test('loaded snapshots without timestamps follow older steps and remain current after archived progress is reconstructed',()=>{
 const requests=[{id:'one',sequence:37,status:'ready',prompt:'Original edit',commit:'one'},{id:'loaded',sequence:48,status:'ready',prompt:'Load snapshot',restoredFrom:'one',commit:'loaded'},{id:'latest',sequence:49,status:'ready',prompt:'Load another snapshot',restoredFrom:'one',commit:'latest'}];
 const groups=compactProgress([{jobId:'one',kind:'edit',stage:'ready',commit:'one',at:'2026-10-06T10:00:00Z'}],null,false,{},requests);
 assert.deepEqual(groups.map(g=>g.request.id),['one','loaded','latest']);assert.equal(groups.at(-1).commit,'latest');assert.equal(groups.at(-1).done,true);assert.equal(groups.at(-1).rows[0].label,'Verze načtena');
});
