import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {spawn,execFile} from 'node:child_process';import {promisify} from 'node:util';import {scryptSync} from 'node:crypto';import {Project} from '../src/project.ts';import {initialTeam,initialImages} from '../src/team.ts';const exec=promisify(execFile);
test('subversion through the dialog appends a numbered publication and updates production',async()=>{
 const data=await mkdtemp(join(tmpdir(),'sitetiller-publish-step-'));const children:any[]=[];let browser:any;
 try{
  const project=new Project(join(data,'project'));await project.init(null);const html=(name:string)=>'<!doctype html><html><head><title>'+name+'</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1>'+name+'</h1></body></html>';
  await project.write({'site/index.html':html('Published')});const base=await project.commit('Published');await project.write({'site/index.html':html('Ready step')});const first=await project.commit('Ready step');await project.write({'site/index.html':html('Later draft')});const head=await project.commit('Later draft');
  const production=join(data,'production.git');await exec('git',['clone','--bare',project.root,production]);await exec('git',['--git-dir='+production,'update-ref','refs/heads/main',base]);const password='test-password-sitetiller',salt='salt';
  await writeFile(join(data,'config.json'),JSON.stringify({password:{salt,hash:scryptSync(password,salt,64).toString('hex')},roles:initialTeam(),imageModels:initialImages(),providers:{openai:{key:''},anthropic:{key:''}},agentArchitecture:3,automaticReasoningPolicy:1,publishedCommit:base,publishedThrough:0,releases:[{id:'release-1',number:1,commit:base,publishedAt:'2026-10-06T12:00:00Z',previousCommit:null,description:'Original',summary:''}],requests:[{id:'first',sequence:1,prompt:'Ready step',status:'ready',commit:first},{id:'later',sequence:2,prompt:'Later draft',status:'ready',commit:head},{id:'failed',sequence:3,prompt:'Later failed attempt',status:'failed'}]}));
  const port=20700+Math.floor(Math.random()*100),pubPort=20900+Math.floor(Math.random()*100),origin='http://127.0.0.1:'+port,url='http://127.0.0.1:'+pubPort+'/publish',env={...process.env,SITETILLER_DATA_DIR:data,HOST:'127.0.0.1',PORT:String(port),SITETILLER_ORIGIN:origin,SITETILLER_PUBLISH_URL:url,SITETILLER_PUBLISH_TOKEN:'test-token',OPENAI_API_KEY:'fixture-key',ANTHROPIC_API_KEY:'fixture-key'};
  children.push(spawn(process.execPath,[fileURLToPath(new URL('./fixtures/provider-server.mjs',import.meta.url))],{env,stdio:'ignore'}),spawn(process.execPath,[fileURLToPath(new URL('../src/publisher.ts',import.meta.url))],{env:{...env,PORT:String(pubPort),SITETILLER_PRODUCTION_GIT:production,SITETILLER_PRODUCTION_URL:''},stdio:'ignore'}));
  for(let i=0;i<100;i++){try{if((await fetch(origin+'/health')).ok&&(await fetch(url)).status===401)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  const login=await fetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})}),cookie=login.headers.get('set-cookie')!.split(';')[0],state=async()=>await(await fetch(origin+'/api/state',{headers:{Cookie:cookie}})).json() as any,post=(input:any)=>fetch(origin+'/api/publish',{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(input)});
  assert.equal((await post({commit:first,expectedHead:base})).status,400);assert.equal((await post({commit:base,expectedHead:head})).status,400);assert.equal(await project.head(),head);
  const {chromium}=await import('playwright');browser=await chromium.launch({...(process.env.SITETILLER_BROWSER_EXECUTABLE?{executablePath:process.env.SITETILLER_BROWSER_EXECUTABLE}:{}),headless:true});const page=await browser.newPage();await page.context().addCookies([{name:'sitetiller',value:cookie.slice('sitetiller='.length),url:origin}]);await page.goto(origin);await page.locator('#timeline .show-version[data-commit="'+first+'"]').click();await page.waitForFunction(()=>document.querySelector('#publish')?.textContent==='Publikovat tento krok');await page.locator('#publish').waitFor({state:'visible'});assert.equal(await page.locator('#publish').textContent(),'Publikovat tento krok');await page.locator('#publish').click();assert.equal(await page.locator('#replace-release-option').isHidden(),false);assert.ok((await page.locator('#confirm-description').textContent())?.includes('Novější rozpracované úpravy zůstanou'));await page.locator('#cancel-publish').click();
  await page.locator('#publish').click();await page.locator('#release-description').fill('Only ready step');assert.equal(await page.locator('#confirm-publish').isDisabled(),false);await page.locator('#confirm-publish').click();await page.waitForFunction(()=>document.querySelector('#confirm-publish')?.disabled||!document.querySelector('#publish-confirm')?.open);try{await page.locator('#publish-confirm').waitFor({state:'hidden',timeout:90000});}catch(error){throw Error(String(error)+'; publication status: '+(await page.locator('#publish-result').textContent())+'; server error: '+((await state()).job?.error||''));}await page.waitForFunction(commit=>document.querySelector('#publish-status')?.textContent==='Aktuální verze 2 · '+commit.slice(0,8),first);let s=await state();assert.equal(s.head,head);assert.equal(s.publishedCommit,first);assert.deepEqual(s.requests.map((r:any)=>r.id),['later','failed']);assert.equal(s.releases.at(-1).number,2);assert.equal(s.releases.at(-1).summary,'Ready step');assert.equal(s.contentChanged,true);assert.ok(s.publishableCommits.includes(head));assert.ok(s.history.some((h:any)=>h.commit===head));assert.equal((await exec('git',['--git-dir='+production,'rev-parse','main:site'])).stdout.trim(),await project.git(['rev-parse',first+':site']));assert.equal((await fetch(origin+'/preview/versions/'+head+'/')).status,200);assert.equal(JSON.parse(await readFile(join(data,'config.json'),'utf8')).publishedThrough,1);
  assert.equal((await post({commit:first,expectedHead:head})).status,400);assert.equal((await post({commit:head,expectedHead:head,createSubversion:true,expectedReleaseId:'wrong',expectedPublishedCommit:first})).status,400);const newLogin=await fetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})}),newCookie=newLogin.headers.get('set-cookie')!.split(';')[0];await page.context().addCookies([{name:'sitetiller',value:newCookie.slice('sitetiller='.length),url:origin}]);await page.locator('#edits-tab').click();await page.locator('#publish').click();await page.locator('#replace-current-release').check();await page.locator('#release-description').fill('Updated detail');assert.equal(await page.locator('#confirm-publish').isDisabled(),false);await page.locator('#confirm-publish').click();await page.waitForFunction(()=>document.querySelector('#confirm-publish')?.disabled||!document.querySelector('#publish-confirm')?.open);try{await page.locator('#publish-confirm').waitFor({state:'hidden',timeout:90000});}catch(error){throw Error(String(error)+'; publication status: '+(await page.locator('#publish-result').textContent())+'; server error: '+((await state()).job?.error||''));}s=await state();await page.locator('#history-toggle').click();assert.equal(await page.locator('.publication-family-group>.publication-card strong').textContent(),'Verze 2.1 – AKTUÁLNÍ');assert.equal(await page.locator('.publication-older .publication-card').isHidden(),true);await page.locator('.publication-older>summary').click();assert.equal(await page.locator('.publication-older .publication-card').isVisible(),true);assert.deepEqual(await page.locator('.publication-older .publication-subversion strong').allTextContents(),['Verze 2.0']);assert.equal(s.releases.length,3);assert.equal(s.releases.at(-1).description,'Updated detail');assert.equal(s.releases.at(-1).minor,1);assert.equal(s.head,head);assert.equal(s.publishedCommit,head);assert.equal(s.requests.length,0);assert.equal(s.releases.at(-1).number,2);assert.equal(s.contentChanged,false);assert.deepEqual(s.publishableCommits,[]);assert.equal((await exec('git',['--git-dir='+production,'rev-parse','main:site'])).stdout.trim(),await project.git(['rev-parse',head+':site']));
 }finally{await browser?.close();for(const child of children)if(child.exitCode===null){const ended=new Promise(r=>child.once('exit',r));child.kill();await ended;}await rm(data,{recursive:true,force:true,maxRetries:5,retryDelay:200});}
});






