import {createServer} from 'node:http';import {websitePolicy} from '../src/site-policy.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawn,execFile} from 'node:child_process';import {promisify} from 'node:util';import {fileURLToPath} from 'node:url';import {scryptSync} from 'node:crypto';import {Project} from '../src/project.ts';import {productionSnapshot} from '../src/production-snapshot.ts';import {productionReleases,storeProductionRelease} from '../src/production-history.ts';import {rebaseWorkspace} from '../src/workspace-history.ts';import {initialTeam,initialImages} from '../src/team.ts';
const exec=promisify(execFile),html=(name:string)=>'<!doctype html><html><head><title>'+name+'</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1>'+name+'</h1></body></html>';
test('production owns numbered versions while workspace is pruned to baseline and newer drafts; history previews and restores use production',async()=>{
 const data=await mkdtemp(join(tmpdir(),'sitetiller-separated-history-')),children:any[]=[];let logs='',live:any,proxy:any,external='',archiveFailure=false;try{
  const work=new Project(join(data,'project'));await work.init(null);await work.write({'site/index.html':html('Zero')});const seed=await work.commit('Seed'),remote=join(data,'production.git'),production=new Project(remote),stage=new Project(join(data,'stage'));await exec('git',['init','--bare','-b','main',remote]);await mkdir(stage.root);await stage.git(['init','-b','main']);const zero=await productionSnapshot(stage,seed,null,work);await stage.git(['push',remote,zero+':refs/heads/main']);await storeProductionRelease(production,{number:0,description:'Baseline',previousCommit:null},zero,seed);await rebaseWorkspace(work,production,zero,seed);
  await mkdir(join(work.root,'site/assets'));await writeFile(join(work.root,'site/assets/discarded.png'),Buffer.from('obsolete draft pixels'));await work.commit('Discarded creative attempt');const obsolete=await work.git(['rev-parse','HEAD:site/assets/discarded.png']);await rm(join(work.root,'site/assets/discarded.png'));await work.write({'site/index.html':html('One')});const first=await work.commit('Work one');await work.write({'site/index.html':html('Two')});const second=await work.commit('Work two');await mkdir(join(data,'uploads'));await writeFile(join(data,'uploads/original.png'),Buffer.from('original upload'));
  live=createServer(async(req:any,res:any)=>{res.setHeader('Content-Security-Policy',websitePolicy);res.end((await production.committedFiles(await production.head()))['site/index.html'].replace(/(<h1>)(.*?)(<\/h1>)/,(_,a,text,b)=>a+(external||text)+b));});await new Promise<void>(resolve=>live.listen(0,'127.0.0.1',resolve));const liveUrl='http://127.0.0.1:'+live.address().port+'/';
  const password='test-password-separated',salt='salt';await writeFile(join(data,'config.json'),JSON.stringify({password:{salt,hash:scryptSync(password,salt,64).toString('hex')},roles:initialTeam(),imageModels:initialImages(),providers:{openai:{key:''},anthropic:{key:''}},agentArchitecture:3,automaticReasoningPolicy:1,historyInitialized:true,separatedHistories:true,draftBaseCommit:zero,lastReviewCommit:zero,publishedCommit:zero,releases:await productionReleases(production),requests:[{id:'one',sequence:1,prompt:'One',status:'ready',commit:first},{id:'two',sequence:2,prompt:'Two',status:'ready',commit:second}]}));
  const port=24500+Math.floor(Math.random()*100),pub=24700+Math.floor(Math.random()*100),origin='http://127.0.0.1:'+port,publishUrl='http://127.0.0.1:'+pub+'/publish',env={...process.env,SITETILLER_DATA_DIR:data,SITETILLER_PRODUCTION_HISTORY_DIR:remote,HOST:'127.0.0.1',PORT:String(port),SITETILLER_ORIGIN:origin,SITETILLER_PUBLISH_URL:publishUrl,SITETILLER_PUBLISH_TOKEN:'test-token',SITETILLER_SITE_URL:'https://example.org/'};
  proxy=createServer(async(req:any,res:any)=>{if(archiveFailure&&req.url==='/archive'){res.writeHead(502,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'Fixture archive failure'}));}let body='';for await(const chunk of req)body+=chunk;const reply=await fetch(new URL(req.url,publishUrl),{method:req.method,headers:{Authorization:req.headers.authorization||'','Content-Type':'application/json'},...(req.method==='POST'?{body}:{})});res.writeHead(reply.status,{'Content-Type':'application/json'});res.end(await reply.text());});await new Promise<void>(resolve=>proxy.listen(0,'127.0.0.1',resolve));env.SITETILLER_PUBLISH_URL='http://127.0.0.1:'+proxy.address().port+'/publish';
  children.push(spawn(process.execPath,[fileURLToPath(new URL('../src/server.ts',import.meta.url))],{env,stdio:'pipe'}),spawn(process.execPath,[fileURLToPath(new URL('../src/publisher.ts',import.meta.url))],{env:{...env,PORT:String(pub),SITETILLER_PRODUCTION_GIT:remote,SITETILLER_PRODUCTION_URL:liveUrl},stdio:'pipe'}));for(const child of children)for(const stream of [child.stdout,child.stderr])stream.on('data',(b:any)=>logs=(logs+b.toString()).slice(-12000));
  for(let i=0;i<100;i++){try{if((await fetch(origin+'/health')).ok&&(await fetch(publishUrl)).status===401)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  const login=await fetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})}),cookie=login.headers.get('set-cookie')!.split(';')[0],state=async()=>await(await fetch(origin+'/api/state',{headers:{Cookie:cookie}})).json() as any,post=async(path:string,input:any)=>{const response=await fetch(origin+'/api/'+path,{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(input)}),value:any=await response.json();assert.equal(response.status,200,JSON.stringify(value)+' '+logs);return value;};
  const pub1=await post('publish',{commit:first,expectedHead:second,stepId:'one',description:'First release'}),one=pub1.release.commit;let s=await state();assert.equal(s.publishedCommit,one);assert.notEqual(one,first);assert.equal(s.requests.length,1);assert.equal(s.requests[0].id,'two');assert.equal(await work.git(['rev-list','--count','HEAD']),'2');assert.equal(await production.git(['rev-list','--count','main']),'2');assert.equal((await work.files())['site/index.html'],html('Two'));await assert.rejects(work.git(['cat-file','-e',first+'^{commit}']));await assert.rejects(production.git(['cat-file','-e',first+'^{commit}']));await assert.rejects(production.git(['cat-file','-e',obsolete]));await assert.rejects(work.git(['cat-file','-e',obsolete]));assert.equal(await work.git(['tag']),'');
  const latest=s.head,release2=await post('publish',{commit:latest,expectedHead:latest}),two=release2.release.commit;s=await state();assert.equal(s.head,two);assert.equal(s.requests.length,0);assert.equal(await work.git(['rev-list','--count','HEAD']),'1');assert.equal(await production.git(['rev-list','--count','main']),'3');assert.deepEqual(s.releases.map((r:any)=>r.number),[0,1,2]);await assert.rejects(work.git(['cat-file','-e',one+'^{commit}']));
  const preview=await fetch(origin+'/preview/versions/'+one+'/');assert.equal(preview.status,200);assert.match(await preview.text(),/<h1>One<\/h1>/);const restore=await post('restore',{commit:one,expectedHead:two,releaseId:release2.release.id,historyMode:'keep'});assert.equal((await work.files())['site/index.html'],html('One'));await assert.rejects(work.git(['cat-file','-e',one+'^{commit}']));
  s=await state();const sub=await post('publish',{commit:restore.commit,expectedHead:s.head,createSubversion:true,expectedReleaseId:s.releases.at(-1).id,expectedPublishedCommit:s.publishedCommit,description:'Restored detail'});assert.equal(sub.release.number,2);assert.equal(sub.release.minor,1);s=await state();assert.equal(s.head,sub.release.commit);assert.equal(await work.git(['rev-list','--count','HEAD']),'1');assert.equal(await production.git(['rev-list','--count','main']),'4');assert.equal(await work.git(['tag']),'');assert.deepEqual(s.releases,await productionReleases(production));
  external='External';const compare=await post('reality/compare',{commit:s.head,expectedHead:s.head});assert.equal(compare.equal,false);assert.equal(compare.source,'hosting-http');const loaded=await post('reality/load',{token:compare.token,expectedHead:s.head,clearPrevious:true,saveVersion:true,versionNumber:3});assert.equal(loaded.savedVersion,3);s=await state();assert.equal(s.releases.at(-1).number,3);assert.equal(s.releases.at(-1).imported,true);assert.match((await work.files())['site/index.html'],/<h1>External<\/h1>/);assert.equal(await work.git(['tag']),'');assert.equal(await production.git(['rev-list','--count','main']),'5');assert.equal(await work.git(['rev-list','--count','HEAD']),'1');
  const equal=await post('reality/compare',{commit:s.head,expectedHead:s.head});assert.equal(equal.equal,true);assert.equal(equal.liveMatchesPublished,true);const blocked=await fetch(origin+'/api/reality/load',{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({token:equal.token,expectedHead:s.head,clearPrevious:true,saveVersion:true,versionNumber:4})});assert.equal(blocked.status,400);assert.match((await blocked.json()).error,/Není co načítat/);assert.equal(await work.head(),s.head);assert.equal(await production.git(['rev-list','--count','main']),'5');
  const reset=await post('restore',{commit:zero,expectedHead:s.head,releaseId:'release-0',historyMode:'clear-all'});s=await state();assert.equal(s.head,zero);assert.equal(s.requests.length,1);assert.equal(await work.git(['rev-list','--count','HEAD']),'1');assert.ok(!s.events.some(e=>e.stage==='published'));assert.equal(s.publishedCommit,loaded.source?.hostingCommit||s.releases.at(-1).commit);
  const stepA=await post('restore',{commit:one,expectedHead:s.head,releaseId:'release-1',historyMode:'keep'});s=await state();const requestA=s.requests.at(-1);
  await post('restore',{commit:two,expectedHead:s.head,releaseId:'release-2',historyMode:'keep'});s=await state();const start=await post('restore',{commit:stepA.commit,expectedHead:s.head,stepId:requestA.id,historyMode:'clear-all'});s=await state();assert.equal(s.head,stepA.commit);assert.equal(s.requests.length,1);assert.equal(s.requests[0].commit,start.commit);assert.equal(await work.git(['rev-list','--count','HEAD']),'1');assert.ok(!s.events.some(e=>e.stage==='published'));assert.match((await work.files())['site/index.html'],/<h1>One<\/h1>/);
  external='Changed again';const beforeFailure=await state(),different=await post('reality/compare',{commit:beforeFailure.head,expectedHead:beforeFailure.head});archiveFailure=true;const failure=await fetch(origin+'/api/reality/load',{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({token:different.token,expectedHead:beforeFailure.head,clearPrevious:true,saveVersion:true,versionNumber:4})});assert.equal(failure.status,400);assert.match((await failure.json()).error,/Fixture archive failure/);s=await state();assert.equal(s.head,beforeFailure.head);assert.deepEqual(s.requests,beforeFailure.requests);assert.deepEqual(s.events,beforeFailure.events);assert.equal(s.busy,false);assert.equal(await production.git(['rev-list','--count','main']),'5');

 }finally{for(const child of children)if(child.exitCode===null){const stopped=new Promise(r=>child.once('exit',r));child.kill();await stopped;}if(proxy)await new Promise<void>(resolve=>proxy.close(()=>resolve()));if(live)await new Promise<void>(resolve=>live.close(()=>resolve()));await rm(data,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});
