import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {spawn} from 'node:child_process';import {scryptSync} from 'node:crypto';
import {Project} from '../src/project.ts';import {initialTeam,initialImages,validTeam} from '../src/team.ts';
test('show versions is read-only, preserves page/assets navigation, and restore alone changes HEAD',async()=>{
 const data=await mkdtemp(join(tmpdir(),'sitetiller-version-ui-'));let child:any,browser:any;
 try{
  const p=new Project(join(data,'project'));await p.init(null);
  const html=(name:string)=>'<!doctype html><html><head><title>'+name+'</title><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"></head><body><h1>'+name+'</h1><a href="/contact/">Contact</a></body></html>';
  await p.write({'site/index.html':html('Old'),'site/contact/index.html':html('Old contact'),'site/style.css':'body{background:rgb(255, 0, 0)}'});const old=await p.commit('Old');
  await p.write({'site/index.html':html('Middle'),'site/contact/index.html':html('Middle contact'),'site/style.css':'body{background:rgb(0, 255, 0)}'});const middle=await p.commit('Middle');
  await p.write({'site/index.html':html('New'),'site/contact/index.html':html('New contact'),'site/style.css':'body{background:rgb(0, 0, 255)}'});const head=await p.commit('New');
  const password='fixture-password-sitetiller',salt='salt';await writeFile(join(data,'config.json'),JSON.stringify({password:{salt,hash:scryptSync(password,salt,64).toString('hex')},providers:{openai:{key:''},anthropic:{key:''}},roles:initialTeam(),imageModels:initialImages(),agentArchitecture:3,publishedCommit:old,releases:[{id:'release-2',number:2,commit:old,publishedAt:'2026-10-05T12:00:00Z',previousCommit:null},{id:'release-3',number:3,commit:old,publishedAt:'2026-10-05T13:00:00Z',previousCommit:old}],requests:[{id:'old',prompt:'Old version',commit:old,status:'ready',sequence:1},{id:'middle',prompt:'Middle version',commit:middle,status:'ready',sequence:2},{id:'new',prompt:'New version',commit:head,status:'ready',sequence:3}]}));
  const port=19800+Math.floor(Math.random()*180),origin='http://127.0.0.1:'+port;
  child=spawn(process.execPath,[fileURLToPath(new URL('./fixtures/provider-server.mjs',import.meta.url))],{env:{...process.env,SITETILLER_DATA_DIR:data,HOST:'127.0.0.1',PORT:String(port),SITETILLER_ORIGIN:origin,OPENAI_API_KEY:'fixture-openai',ANTHROPIC_API_KEY:'fixture-claude'},stdio:'ignore'});
  let ready=false;for(let i=0;i<200;i++){try{if((await fetch(origin+'/health')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
  const {chromium}=await import('playwright');browser=await chromium.launch({...(process.env.SITETILLER_BROWSER_EXECUTABLE?{executablePath:process.env.SITETILLER_BROWSER_EXECUTABLE}:{}),headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin);await page.locator('#password').fill(password);await page.locator('#login-form button').click();await page.locator('#workspace').waitFor({state:'visible'});
  await page.locator('#prompt').fill('Rozpracované zadání');
  for(const width of [1440,1000,390]){await page.setViewportSize({width,height:1000});const header=await page.locator('.studio-header').boundingBox(),aside=await page.locator('aside').boundingBox(),preview=await page.locator('.preview-panel').boundingBox();assert.ok(header&&aside&&preview);assert.equal(header.y,0);assert.ok(Math.abs(header.width-aside.width)<1);if(width>900)assert.equal(preview.y,0);assert.ok(await page.locator('.studio-header').evaluate(n=>n.scrollWidth<=n.clientWidth));}
  await page.setViewportSize({width:1440,height:1000});assert.equal(await page.getByRole('button',{name:'Nastavení',exact:true}).locator('svg').count(),1);assert.equal(await page.getByRole('button',{name:'Odhlásit',exact:true}).locator('svg').count(),1);
  await page.locator('#history-toggle').click();assert.equal(await page.locator('#prompt-form').isHidden(),true);assert.equal(await page.locator('#history-toggle').getAttribute('aria-selected'),'true');
  await page.locator('#history-toggle').press('ArrowLeft');assert.equal(await page.locator('#edits-tab').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#prompt').inputValue(),'Rozpracované zadání');await page.locator('#edits-tab').press('ArrowRight');assert.equal(await page.locator('#history-toggle').getAttribute('aria-selected'),'true');
  const historyBox=await page.locator('#history').boundingBox();assert.ok(historyBox&&historyBox.height>800);
  const oldButton=()=>page.locator('#history .publication-card[data-release-id="release-3"]'),newButton=()=>page.locator('#timeline .show-version[data-commit="'+head+'"]');
  await newButton().waitFor({state:'attached'});assert.equal(await page.locator('.preview-active').count(),1);assert.equal(await newButton().isHidden(),true);assert.equal(await page.locator('#publish-status').textContent(),'Aktuální návrh · '+head.slice(0,8));assert.equal(await page.locator('#publish-note').textContent(),'Zatím nepublikovaná verze.');assert.equal(await page.locator('#current-draft').count(),0);assert.ok(!(await page.locator('#preview').getAttribute('sandbox'))?.includes('allow-same-origin'));assert.equal(await oldButton().isDisabled(),false);
  await oldButton().click();await page.waitForFunction(()=>!document.querySelector('#restore-preview')?.hasAttribute('hidden'));
  const frame=page.frameLocator('#preview');await frame.getByRole('heading',{name:'Old',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('#project-title')?.textContent==='Old');assert.equal(await page.locator('#project-title').isVisible(),true);await frame.locator('body').evaluate(async()=>{for(let i=0;i<100&&getComputedStyle(document.body).backgroundColor!=='rgb(255, 0, 0)';i++)await new Promise(r=>setTimeout(r,50));});assert.equal(await frame.locator('body').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 0, 0)');
  assert.equal(await oldButton().isVisible(),true);assert.equal(await oldButton().getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#publish-status').textContent(),'Aktuální verze 3 · '+old.slice(0,8));assert.equal(await page.locator('#current-draft').count(),0);assert.equal(await page.locator('.preview-active').count(),1);assert.equal(await page.locator('#run').isDisabled(),true);assert.equal(await p.head(),head);
  const duplicateButton=()=>page.locator('#history .publication-card[data-release-id="release-2"]');assert.equal(await duplicateButton().isVisible(),true);await duplicateButton().click();await page.waitForFunction(()=>document.querySelector('#history .publication-card[data-release-id="release-2"]')?.getAttribute('aria-pressed')==='true');assert.equal(await duplicateButton().isVisible(),true);assert.equal(await duplicateButton().getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#publish-status').textContent(),'Starší verze 2 · '+old.slice(0,8));assert.equal(await page.locator('#history .preview-active').count(),1);assert.equal(await page.locator('#history .preview-active').getAttribute('data-release-id'),'release-2');assert.equal(await p.head(),head);await oldButton().click();await page.waitForFunction(()=>document.querySelector('#history .publication-card[data-release-id="release-3"]')?.getAttribute('aria-pressed')==='true');assert.equal(await duplicateButton().isVisible(),true);assert.equal(await page.locator('#history .preview-active').getAttribute('data-release-id'),'release-3');
  await frame.getByRole('link',{name:'Contact'}).click();await frame.getByRole('heading',{name:'Old contact'}).waitFor();await page.waitForFunction(()=>document.querySelector('#project-title')?.textContent==='Old contact');await frame.locator('body').evaluate(async()=>{for(let i=0;i<100&&getComputedStyle(document.body).backgroundColor!=='rgb(255, 0, 0)';i++)await new Promise(r=>setTimeout(r,50));});assert.equal(await frame.locator('body').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 0, 0)');
  assert.equal((await fetch(origin+'/preview/versions/'+ 'a'.repeat(40)+'/')).status,404);
  await oldButton().click();await frame.getByRole('heading',{name:'New',exact:true}).waitFor();assert.equal(await oldButton().getAttribute('aria-pressed'),'false');await oldButton().click();await frame.getByRole('heading',{name:'Old',exact:true}).waitFor();await page.locator('#edits-tab').click();await frame.getByRole('heading',{name:'New',exact:true}).waitFor();assert.equal(await page.locator('.preview-active').count(),1);assert.equal(await page.locator('#restore-preview').isHidden(),true);assert.equal(await p.head(),head);
  const middleCard=page.locator('#timeline .progress-group[data-commit="'+middle+'"]');await middleCard.locator('.chat-request').click();await frame.getByRole('heading',{name:'Middle',exact:true}).waitFor();const beforeSummary=await page.locator('#preview').getAttribute('src');assert.equal(await middleCard.locator('summary').count(),0); await middleCard.locator('.chat-answer').click(); await frame.getByRole('heading',{name:'New',exact:true}).waitFor(); await middleCard.locator('.chat-request').click(); await frame.getByRole('heading',{name:'Middle',exact:true}).waitFor();assert.equal(await page.locator('#preview').getAttribute('src'),beforeSummary);assert.equal(await newButton().isVisible(),true);assert.equal(await page.locator('#publish-status').textContent(),'Předchozí krok návrhu');assert.equal(await page.locator('#publish-note').textContent(),'Vraťte se na tento krok pro další úpravy, nebo přepněte na Aktuální návrh.');await page.locator('#timeline .show-version[data-commit="'+middle+'"]').click();await frame.getByRole('heading',{name:'New',exact:true}).waitFor();assert.equal(await p.head(),head);
  await page.locator('#history-toggle').click();await oldButton().click();await frame.getByRole('heading',{name:'Old',exact:true}).waitFor();await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-clear-previous').isChecked(),true);await page.locator('#restore-clear-previous').check();assert.ok((await page.locator('#restore-history-note').textContent())?.includes('kroky se odstraní'));await page.locator('#cancel-restore').click();assert.equal(await p.head(),head);await page.locator('#restore-preview').click();assert.equal(await page.locator('#restore-clear-previous').isChecked(),true);await page.locator('#restore-clear-previous').uncheck();await page.locator('#confirm-restore').click();await page.locator('#restore-confirm').waitFor({state:'hidden'});await frame.getByRole('heading',{name:'Old',exact:true}).waitFor();await page.locator('#restore-preview').waitFor({state:'hidden'});assert.notEqual(await p.head(),head);assert.equal(await page.locator('#restore-preview').isHidden(),true);const loadedHead=await p.head();const lastGroup=page.locator('#timeline .progress-group').last();assert.equal(await lastGroup.getAttribute('data-commit'),loadedHead);assert.equal(await lastGroup.getAttribute('data-current-draft'),'true');assert.equal(await lastGroup.locator('.show-version').isHidden(),false);assert.equal(await lastGroup.evaluate(n=>n.classList.contains('preview-active')),true);assert.equal(await page.locator('#publish-status').textContent(),'Aktuální návrh · '+loadedHead.slice(0,8));
  const team=initialTeam();team.primary.reasoningEffort='auto';team.verify.reasoningEffort='auto';team.escalation.reasoningEffort='low';assert.equal(validTeam(team),true);team.escalation.reasoningEffort='auto';assert.equal(validTeam(team),false);
  assert.deepEqual(errors,[]);
 }finally{await browser?.close();if(child){const exited=new Promise(r=>child.once('exit',r));child.kill();await exited;}await rm(data,{recursive:true,force:true,maxRetries:5,retryDelay:200});}
});




