import {mkdtemp,mkdir,rename,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {Project} from './project.ts';import {raster} from './images.ts';import {safeSitePath} from './core.ts';
export async function rebaseWorkspace(work:Project,production:Project,published:string,selected:string,retain?:string[]){
 const head=await work.head(),newer=(await work.git(['rev-list','--first-parent','--reverse',selected+'..'+head])).split('\n').filter(commit=>!!commit&&(!retain||retain.includes(commit))),parent=join(work.root,'..'),temporary=await mkdtemp(join(parent,'workspace-next-'));const fresh=new Project(temporary),mapping:Record<string,string>={[selected]:published};
 try{
  await fresh.git(['init','-b','main']);await fresh.git(['config','core.autocrlf','false']);await fresh.git(['config','user.name','SiteTiller']);await fresh.git(['config','user.email','sitetiller@localhost']);await fresh.git(['fetch','--depth=1',production.root,published]);await fresh.git(['checkout','-B','main','FETCH_HEAD']);
  for(const old of newer){const files=await work.committedFiles(old);await fresh.writeSnapshot(files);for(const path of Object.keys(files).filter(raster)){await mkdir(join(safeSitePath(temporary,path),'..'),{recursive:true});await writeFile(safeSitePath(temporary,path),await work.binary(old,path));}await fresh.git(['add','site']);await fresh.git(['commit','--allow-empty','-m',await work.git(['show','-s','--format=%s',old])]);mapping[old]=await fresh.head();if(await fresh.git(['rev-parse','HEAD:site'])!==await work.git(['rev-parse',old+':site']))throw Error('Novější návrh se při uzavření historie změnil.');}
  if(await work.head()!==head)throw Error('Návrh se mezitím změnil.');const retired=join(parent,'workspace-retired-'+Date.now());await rename(work.root,retired);try{await rename(temporary,work.root);}catch(e){await rename(retired,work.root);throw e;}await rm(retired,{recursive:true,force:true,maxRetries:3,retryDelay:100});return {head:await work.head(),mapping};
 }finally{await rm(temporary,{recursive:true,force:true,maxRetries:3,retryDelay:100});}
}
